version: "3.7"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      - DB_NAME=friends_db
      - DB_USER=friends_user
      - DB_PASSWORD=friends_password
      - DB_HOST=postgres
      - DB_PORT=5432
      - DEBUG=False
    depends_on:
      - postgres

  postgres:
    image: postgres:15.2
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=friends_user
      - POSTGRES_PASSWORD=friends_password
      - POSTGRES_DB=friends_db

volumes:
  postgres_data:
