version: "3.7"
services:
  postgres:
    image: postgres:15.2
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - ${BILLING_DB_PORT:-5432}:5432
    env_file:
      - .env
    environment:
      - POSTGRES_USER=friends_user
      - POSTGRES_PASSWORD=friends_password
      - POSTGRES_DB=friends_db

volumes:
  postgres_data:
  rabbit_data:
